proxy:
  chp:
    nodeSelector:
      kubernetes.io/os: linux

hub:
  cookieSecret: "generate-a-secure-random-string"
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      server_address: "://codingworkshop.net" # Your Managed AD DNS name or IP addresses
      server_port: 389
      bind_dn_template: "CN={username},OU=Users,OU=CORP,DC=corp,DC=codingworkshop,DC=net"
      user_attribute: "sAMAccountName"
      allowed_groups:
        - "OU=Groups,OU=CORP,DC=corp,DC=codingworkshop,DC=net"
  nodeSelector:
    kubernetes.io/os: linux

singleuser:
  cloudMetadata:
    blockWithIptables: false
  image:
    name: jupyter/datascience-notebook
    tag: latest
  nodeSelector:
    kubernetes.io/os: linux
