proxy:
  secretToken: "f0e017c6a1948c8e4291fe187f67b3e25da010d8ca0c7722818dd0a8ebf31464"
  service:
    type: ClusterIP

hub:
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      server_address: "corp.codingworkshop.net"
      server_port: 389
      bind_dn_template: "CN={username},OU=Users,OU=CORP,DC=corp,DC=codingworkshop,DC=net"
      user_attribute: "sAMAccountName"
      allowed_groups:
        - "OU=Groups,OU=CORP,DC=corp,DC=codingworkshop,DC=net"

singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest
  cpu:
    limit: 2
    guarantee: 1
  memory:
    limit: 2Gi
    guarantee: 1Gi
  storage:
    type: "none"
    extraVolumes:
      - name: scratch-volume
        emptyDir: {}
    extraVolumeMounts:
      - name: scratch-volume
        mountPath: /var/run/jupyter

scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 1
