pythonJob:
  enabled: false
  name: "python-job"
  scriptContent: ""
  image:
    repository: jupyter/datascience-notebook
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    limits:
      cpu: 0.5
      memory: 2Gi
    requests:
      cpu: 0.25
      memory: 1Gi
